# Generated by Django 5.1 on 2024-08-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('top selling', 'top selling')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('SmartPhone', 'SmartPhone'), ('Laptops', 'Laptops'), ('Camera', 'Camera'), ('Accessories', 'Assecories')], default='SmartPhone', max_length=30),
        ),
    ]
