# Generated by Django 5.1 on 2024-08-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_product_status_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='oldprice',
            field=models.IntegerField(default=34499),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('SmartPhone', 'SmartPhone'), ('Laptop', 'Laptop'), ('Camera', 'Camera'), ('Accessories', 'Assecories')], default='SmartPhone', max_length=30),
        ),
    ]
